import type { TypedControlConfig } from '@stanko/ctrls';

export const config = [
  {
    type: 'boolean',
    name: 'debug',
    defaultValue: true,
    isRandomizationDisabled: true,
  },
  {
    name: 'size',
    type: 'range',
    isRandomizationDisabled: true,
    min: 50,
    step: 1,
    max: 400,
    defaultValue: 145,
  },
  {
    name: 'minDistance',
    type: 'range',
    isRandomizationDisabled: true,
    min: 0.5,
    step: 0.1,
    max: 3,
    defaultValue: 0.5,
  },
  {
    name: 'pointsPerLine',
    type: 'range',
    min: 1,
    step: 1,
    max: 50,
    defaultValue: 2,
  },
  {
    name: 'segmentLength',
    type: 'range',
    min: 0.2,
    step: 0.1,
    max: 10,
    defaultValue: 2,
  },
  {
    name: 'lineWidth',
    type: 'range',
    isRandomizationDisabled: true,
    min: 0.1,
    step: 0.05,
    max: 3,
    defaultValue: 1,
  },
  {
    name: 'whiteOnly',
    type: 'boolean',
    defaultValue: false,
  },
  {
    name: 'moonPhase',
    type: 'range',
    isRandomizationDisabled: true,
    min: 1,
    step: 1,
    max: 5,
    defaultValue: 3,
  },
  {
    name: 'noiseScale',
    type: 'range',
    isRandomizationDisabled: true,
    min: 1,
    step: 1,
    max: 5000,
    defaultValue: 1000,
  },
  {
    name: 'mainSeed',
    type: 'seed',
  },
  {
    name: 'noiseSeed',
    type: 'seed',
  },
  {
    name: 'easing',
    type: 'easing',
    defaultValue: [0.73, 0.15, 0.87, 0.62],
    presets: {
      DEFAULT: [0.73, 0.15, 0.87, 0.62],
      EASE: [0.25, 0.1, 0.25, 1],
      LINEAR: [0, 0, 1, 1],
      EASE_IN: [0.42, 0, 1, 1],
      EASE_OUT: [0, 0, 0.58, 1],
      EASE_IN_OUT: [0.42, 0, 0.58, 1],
    },
  },
  {
    type: 'boolean',
    name: 'plottingHelpers',
    defaultValue: false,
    isRandomizationDisabled: true,
  },
] as const satisfies readonly TypedControlConfig[];
